import Config

# Configure your database (Regular DuckDB)
config :sample_phoenix, SamplePhoenix.Repo,
  database: Path.expand("../sample_phoenix_dev.duckdb", __DIR__),
  # DuckDB only allows one writer at a time
  pool_size: 1,
  queue_target: 5000,
  queue_interval: 1000,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# Configure DuckLake database (separate DuckDB instance for analytics/demo data)
# Note: pool_size: 1 is REQUIRED because DuckDB only allows one writer at a time
#
# This example shows how to use DuckDB secrets, attach databases, and configs.
# For full DuckLake functionality, you can:
# 1. Create WebDAV secrets for Hetzner Storagebox access
# 2. Attach DuckLake databases with remote storage
# 3. Configure database-specific settings
#
# Simple local configuration (works out of the box):
config :sample_phoenix, SamplePhoenix.DuckLakeRepo,
  database: Path.expand("../sample_phoenix_ducklake_dev.duckdb", __DIR__),
  pool_size: 1,
  queue_target: 5000,
  queue_interval: 1000,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# Advanced configuration example (requires WebDAV credentials):
# config :sample_phoenix, SamplePhoenix.DuckLakeRepo,
#   database: Path.expand("../sample_phoenix_ducklake_dev.duckdb", __DIR__),
#   pool_size: 1,
#   queue_target: 5000,
#   queue_interval: 1000,
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true,
#
#   # Create secrets for WebDAV/S3 access
#   secrets: [
#     {:hetzner_storagebox,
#      {
#        [
#          username: System.get_env("STORAGEBOX_USERNAME") || "your-username",
#          password: System.get_env("STORAGEBOX_PASSWORD") || "your-password"
#        ],
#        [
#          type: :webdav,
#          scope: "storagebox://#{System.get_env("STORAGEBOX_USERNAME") || "your-username"}"
#        ]
#      }}
#   ],
#
#   # Attach DuckLake databases
#   attach: [
#     # Local DuckLake with remote parquet storage on WebDAV
#     {
#       "ducklake:sample_phoenix_dev.ducklake",
#       [
#         as: :phoenix_db,
#         options: [
#           DATA_PATH: "storagebox://#{System.get_env("STORAGEBOX_USERNAME") || "your-username"}/phoenix_db"
#         ]
#       ]
#     }
#   ],
#
#   # Set database-specific configuration
#   configs: [
#     phoenix_db: [
#       data_inlining_row_limit: 10000,
#       parquet_compression: :zstd,
#       parquet_compression_level: 20,
#       parquet_version: 2
#     ]
#   ],
#
#   # Use attached database as default
#   use: :phoenix_db

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sample_phoenix, SamplePhoenixWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "187nuUOtsU3S1LEtOWHSTWNyyieuteUff5K45QWMM2JTmEYdQ+bWahpd1P2yibUs",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sample_phoenix, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sample_phoenix, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :sample_phoenix, SamplePhoenixWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/sample_phoenix_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :sample_phoenix, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
