import Config

# Helper function to require environment variables
require_env = fn var_name ->
  System.get_env(var_name) ||
    raise """
    Environment variable #{var_name} is not set!

    Please set it before running migrations or starting the server:
    export #{var_name}="your_value"
    """
end

# Configure your database (Regular DuckDB)
config :sample_phoenix, SamplePhoenix.Repo,
  database: Path.expand("../sample_phoenix_dev.duckdb", __DIR__),
  # DuckDB only allows one writer at a time
  pool_size: 1,
  queue_target: 5000,
  queue_interval: 1000,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Disable query logging (set to false or :info/:warning/:error)
  log: false

# Configure DuckLake database (separate DuckDB instance for analytics/demo data)
# Note: pool_size: 1 is REQUIRED because DuckDB only allows one writer at a time
#
# This configuration supports two modes:
# 1. Basic mode (no env vars): Simple DuckLake database for local use
# 2. Advanced mode (with STORAGEBOX_USER and STORAGEBOX_PASSWORD):
#    Full DuckLake with WebDAV remote storage

# Check if WebDAV credentials are available
webdav_enabled =
  System.get_env("STORAGEBOX_USER") != nil && System.get_env("STORAGEBOX_PASSWORD") != nil

# Base configuration for DuckLake
base_ducklake_config = [
  database: Path.expand("../sample_phoenix_ducklake_dev.duckdb", __DIR__),
  pool_size: 1,
  queue_target: 5000,
  queue_interval: 1000,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  migration_lock: false,
  log: false
]

# Advanced WebDAV configuration (only if credentials are set)
advanced_ducklake_config =
  if webdav_enabled do
    storagebox_user = require_env.("STORAGEBOX_USER")
    storagebox_password = require_env.("STORAGEBOX_PASSWORD")

    [
      # Install and load DuckDB extensions for remote storage
      extensions: [
        :httpfs,
        {:netquack, source: :community},
        {:webdavfs, source: :community}
      ],

      # Create secrets for WebDAV access
      secrets: [
        {:hetzner_storagebox,
         [
           username: storagebox_user,
           password: storagebox_password,
           type: :webdav,
           scope: "storagebox://#{storagebox_user}"
         ]}
      ],

      # Attach DuckLake with remote parquet storage
      attach: [
        {
          "ducklake:sample_phoenix_dev.ducklake",
          [
            as: :phoenix_db,
            options: [
              DATA_PATH: "storagebox://#{storagebox_user}/phoenix_db"
            ]
          ]
        }
      ],

      # Set database-specific configuration for DuckLake
      configs: [
        phoenix_db: [
          data_inlining_row_limit: 10000,
          parquet_compression: :zstd,
          parquet_compression_level: 20,
          parquet_version: 2
        ]
      ],

      # Use attached database as default
      use: :phoenix_db
    ]
  else
    # Basic configuration without WebDAV
    []
  end

# Merge base and advanced configuration
config :sample_phoenix,
       SamplePhoenix.DuckLakeRepo,
       Keyword.merge(base_ducklake_config, advanced_ducklake_config)

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sample_phoenix, SamplePhoenixWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # gitleaks:allow - development secret, safe to commit
  secret_key_base: "187nuUOtsU3S1LEtOWHSTWNyyieuteUff5K45QWMM2JTmEYdQ+bWahpd1P2yibUs",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sample_phoenix, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sample_phoenix, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :sample_phoenix, SamplePhoenixWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/sample_phoenix_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :sample_phoenix, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Note: Logger level is configured in config/runtime.exs
# Use DEBUG=1 to enable debug logs at runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
