defmodule SamplePhoenix.DuckLakeRepo.Migrations.CreateJobs do
  use Ecto.Migration

  def change do
    # DuckLake doesn't support primary keys:
    # https://ducklake.select/docs/stable/duckdb/unsupported_features
    create table(:jobs, primary_key: false) do
      add :url, :string

      # DuckLake doesn't yet support autogenerated timestamps because default values can only be literals and not NOW()
      # https://github.com/duckdb/ducklake/issues/297
      # timestamps(type: :utc_datetime)
    end
  end
end
